name: Reusable Workflow

on:
  workflow_call:
    inputs:
      market:
        description: "The market to execute"
        required: true
        type: string
      steps:
        description: "Map of steps to execute"
        required: true
        type: string

jobs:
  execute_steps:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Step 1
        if: ${{ inputs.steps.step_1 == 'true' }}
        run: echo "Step 1 executed"

      - name: Execute Step 2
        if: ${{ inputs.steps.step_2 == 'true' }}
        run: echo "Step 2 executed"

      - name: Execute Step 3
        if: ${{ inputs.steps.step_3 == 'true' }}
        run: echo "Step 3 executed"
