name: Reusable Workflow

on:
  workflow_call:
    inputs:
      market:
        description: "The market to execute"
        required: true
        type: string
      step_1:
        description: "Whether to execute step 1"
        required: true
        default: "false"
        type: string
      step_2:
        description: "Whether to execute step 2"
        required: true
        default: "false"
        type: string
      step_3:
        description: "Whether to execute step 3"
        required: true
        default: "false"
        type: string

jobs:
  execute_steps:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Step 1
        if: ${{ inputs.step_1 == 'true' }}
        run: echo "Step 1 executed"

      - name: Execute Step 2
        if: ${{ inputs.step_2 == 'true' }}
        run: echo "Step 2 executed"

      - name: Execute Step 3
        if: ${{ inputs.step_3 == 'true' }}
        run: echo "Step 3 executed"
