name: Caller Workflow

on: push

jobs:
  call_reusable_workflow_for_market1:
    uses: ./.github/workflows/all-in-action.yml
    with:
      market: "market1"
      step_1: "true"
      step_2: "true"
      step_3: "false"

  call_reusable_workflow_for_market2:
    uses: ./.github/workflows/all-in-action.yml
    with:
      market: "market2"
      step_1: "false"
      step_2: "false"
      step_3: "true"
