name: CI/CD Pipeline

on:
  push:
    branches:
      - mai

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Step Inicial
        id: hello
        uses: Dilson1502/docker-action-release@v1
        with:
          who-to-great: "Dilson"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build the project
        run: npm run build  # Adjust this command as needed

      - name: Deploy (optional)
        if: github.ref == 'refs/heads/main'  # Deploy only on the main branch
        run: |
          echo "Deploying to production..."
          # Add your deployment command here
