on:
  push:
name: action
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Step Inicial
        id: hello
        uses: dilson1502/docker-action-release@v2
        with:
          who-to-greet: "Dilson"
      - name: Step Final
        run: echo "La fecha fue ${{ steps.hello.outputs.time}}"


